spring.application.name=alarm-backend

# ---- MongoDB Atlas ----
spring.data.mongodb.uri= your uri

# ---- JWT ----
jwt.secret=${JWT_SECRET:change-this-to-a-long-random-secret-in-env-vars}
jwt.expiration-ms=86400000

# ---- Anthropic Claude API ---
gemini.api.key= YOUR_GCP_API_KEY_HERE
gemini.api.url= your url

# ---- Timezone ----
app.timezone=Asia/Kolkata

# ---- Server ----
server.port=${PORT:8080}
